### ISSUE TITLE
Build fails: "No such property: sonatypeUsername"

### ISSUE THREAD

**Issue by Conal-Tuohy** [ndw/xmlcalabash1-docs#4]
I'm new to Gradle, so excuse me if I've made an obvious error.

I've installed Gradle 2 and I issue the command `gradle` in the xmlcalabash root folder to attempt a build. I get the following error:

```
FAILURE: Build failed with an exception.

* Where:
Build file '/usr/src/xmlcalabash1/build.gradle' line: 426

* What went wrong:
A problem occurred evaluating root project 'xmlcalabash1'.
> No such property: sonatypeUsername for class: org.gradle.api.publication.maven.internal.deployer.DefaultGroovyMavenDeployer

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 7.62 secs
```

**Comment by ndw** [comment]
You've filed this issue on the xmlcalabash1-docs repo, but I think the problem you're reporting actually occurs in the xmlcalabash1 repo...

Do you really want to upload to the Sonatype maven repo?

If you do, you'll have to provide a username and password. I put it in my ~/.gradle/gradle.properties file.

If not, just avoid the "uploadArchives" target.

**Comment by Conal-Tuohy** [comment]
I don't know if this is an error in the build process, or just that the docs don't tell me what I need to know (I think probably the latter). I am just trying to build an xmlcalabash distribution locally; not upload it anywhere.

Reading the xmlcalabash docs again and the gradle docs, it implies I should issue this command:

`gradle dist`

... but this just gives me a sonatypeUsername error. If I try to avoid the "uploadArchives" target:

`gradle dist -x uploadArchives`

I get the same error.

**Comment by Conal-Tuohy** [comment]
OK it seems that the build requires you to have a `sonatypeUsername` and `sonatypePassword` defined, whether you use them or not (i.e. the requirement does not depend on which gradle task you run). I think the docs probably should make some note of this.

I got past my problem by editing `xmlcalabash1/gradle.properties` and adding:

```
sonatypeUsername=
sonatypePassword=
```

According to the [Gradle docs](https://docs.gradle.org/current/userguide/build_environment.html), properties can be defined in multiple places, and `gradle.properties` in the `gradle user home` will override `gradle.properties` in the project's build directory. This implies to me that the `gradle.properties` in the calabash repo should include null username and password as above. In which case I should have raised this issue in the other repo. ;-)

**Comment by Conal-Tuohy** [comment]
Fixed by merge above
